const notificationEvents = {
    EVENT_START: 'Notification/EVENT_START', // Deprecated in favor of EVENT_USER_REWARD
    EVENT_RESOLVE: 'Notification/EVENT_RESOLVE', // Deprecated in favor of EVENT_USER_REWARD
    EVENT_CANCEL: 'Notification/EVENT_CANCEL', // Deprecated in favor of EVENT_USER_REWARD
    EVENT_NEW_REWARD: 'Notification/EVENT_NEW_REWARD', // Deprecated in favor of EVENT_USER_REWARD
    // User-related events
    EVENT_USER_SIGNED_IN: `Notification/EVENT_USER_SIGNED_IN`,
    EVENT_USER_SIGNED_UP: `Notification/EVENT_USER_SIGNED_UP`,
    EVENT_USER_FORGOT_PASSWORD: `Notification/EVENT_USER_FORGOT_PASSWORD`,
    EVENT_USER_UPLOADED_PICTURE: `Notification/EVENT_USER_UPLOADED_PICTURE`,
    EVENT_USER_CHANGED_USERNAME: `Notification/EVENT_USER_CHANGED_USERNAME`,
    EVENT_USER_CHANGED_NAME: `Notification/EVENT_USER_CHANGED_NAME`,
    EVENT_USER_CHANGED_PASSWORD: `Notification/EVENT_USER_CHANGED_PASSWORD`,
    EVENT_USER_UPDATED_EMAIL_PREFERENCES: `Notification/EVENT_USER_UPDATED_EMAIL_PREFERENCES`,
    EVENT_USER_SET_CURRENCY: `Notification/EVENT_USER_SET_CURRENCY`,
    EVENT_USER_REWARD: 'Notification/EVENT_USER_REWARD',
    // Event related events
    EVENT_ONLINE: 'Notification/EVENT_ONLINE',
    EVENT_OFFLINE: 'Notification/EVENT_OFFLINE',
    EVENT_NEW: 'Notification/EVENT_NEW',
    EVENT_UPDATED: 'Notification/EVENT_UPDATED',
    EVENT_NEW_BET: 'Notification/EVENT_NEW_BET',
    // Bet related events
    EVENT_BET_PLACED: 'Notification/EVENT_BET_PLACED',
    EVENT_BET_STARTED: 'Notification/EVENT_BET_STARTED',
    EVENT_BET_CASHED_OUT: 'Notification/EVENT_BET_CASHED_OUT',
    EVENT_BET_RESOLVED: 'Notification/EVENT_BET_RESOLVED',
    EVENT_BET_EVALUATED: 'Notification/EVENT_BET_EVALUATED',
    EVENT_BET_DISPUTED: 'Notification/EVENT_BET_DISPUTED',
    EVENT_BET_CANCELED: 'Notification/EVENT_BET_CANCELED',
    // ###### REWARDS BEGIN ######
    // [Reward system] General related events
    EVENT_REWARD_SIGN_UP_INFLUENCER: 'Notification/EVENT_REWARD_SIGN_UP_INFLUENCER',
    EVENT_REWARD_REFER_FRIEND: 'Notification/EVENT_REWARD_REFER_FRIEND',
    EVENT_REWARD_SHARE_LINK: 'Notification/EVENT_REWARD_SHARE_LINK',
    EVENT_REWARD_ANSWER_FEEDBACK: 'Notification/EVENT_REWARD_ANSWER_FEEDBACK',
    EVENT_REWARD_DAILY_LOGIN: 'Notification/EVENT_REWARD_DAILY_LOGIN',
    EVENT_REWARD_USER_INACTIVITY_COME_BACK: 'Notification/EVENT_REWARD_USER_INACTIVITY_COME_BACK',
    // [Reward system] Easter eggs related events
    EVENT_REWARD_EG_BET_MAX_STAKE_IN_ROW: 'Notification/EVENT_REWARD_EG_BET_MAX_STAKE_IN_ROW',
    EVENT_REWARD_EG_ROSI_GAME_X_TIMES: 'Notification/EVENT_REWARD_EG_ROSI_GAME_X_TIMES',
    EVENT_REWARD_EG_USER_ACTIVE_MORE_THAT_X: 'Notification/EVENT_REWARD_EG_USER_ACTIVE_MORE_THAT_X',
    EVENT_REWARD_EG_USER_PLAY_X_DAYS_IN_ROW: 'Notification/EVENT_REWARD_EG_USER_PLAY_X_DAYS_IN_ROW',
    EVENT_REWARD_EG_USER_PROVIDE_BIRTH_DATE: 'Notification/EVENT_REWARD_EG_USER_PROVIDE_BIRTH_DATE',
    EVENT_REWARD_EG_USER_CHECK_IN_X_DIF_CHATS: 'Notification/EVENT_REWARD_EG_USER_CHECK_IN_X_DIF_CHATS',
    EVENT_REWARD_EG_USER_BET_X_TIMES_SOCIETY_CATS: 'Notification/EVENT_REWARD_EG_USER_BET_X_TIMES_SOCIETY_CATS',
    EVENT_REWARD_EG_USER_PROVIDE_FEEDBACK: 'Notification/EVENT_REWARD_EG_USER_PROVIDE_FEEDBACK',
    // [Reward system] Weekly Leader Board related events
    EVENT_REWARD_WEEKLY_LEADERBOARD_X: 'Notification/EVENT_REWARD_WEEKLY_LEADERBOARD_X',
    // [Reward system] Monthly Leader Board related events
    EVENT_REWARD_MONTHLY_LEADERBOARD_X: 'Notification/EVENT_REWARD_MONTHLY_LEADERBOARD_X',
    // [Reward system] Milestones related events
    EVENT_REWARD_MS_PLACE_BET_X_TIMES: 'Notification/EVENT_REWARD_MS_PLACE_BET_X_TIMES',
    EVENT_REWARD_MS_PLAY_ROSI_GAME_X_TIMES: 'Notification/EVENT_REWARD_MS_PLAY_ROSI_GAME_X_TIMES',
    EVENT_REWARD_MS_REFER_FRIENDS_X_TIMES: 'Notification/EVENT_REWARD_MS_REFER_FRIENDS_X_TIMES',
    // [Reward system] Stages (Badges) related events
    EVENT_REWARD_BADGE_PLACE_X_BETS: 'Notification/EVENT_REWARD_BADGE_PLACE_X_BETS',
    EVENT_REWARD_BADGE_PLACE_ROSI_GAME_X_TIMES: 'Notification/EVENT_REWARD_BADGE_PLACE_ROSI_GAME_X_TIMES',
    EVENT_REWARD_BADGE_TURNOVER_X_PERCENT: 'Notification/EVENT_REWARD_BADGE_TURNOVER_X_PERCENT',
    EVENT_REWARD_BADGE_REFER_FRIENDS_X_TIMES: 'Notification/EVENT_REWARD_BADGE_REFER_FRIENDS_X_TIMES',
    // [Reward system] NOTIFICATIONS, general notification event for rewards
    EVENT_REWARD_NOTIFY_ABOUT_X: 'Notification/EVENT_REWARD_NOTIFY_ABOUT_X'
    // ###### REWARDS END ######
};

exports.notificationEvents = notificationEvents

const eventTypes = [...Object.values(notificationEvents)]

exports.universalEventTypes = eventTypes

