const notificationEvents = {
    EVENT_START: 'Notification/EVENT_START', // Deprecated in favor of EVENT_USER_REWARD
    EVENT_RESOLVE: 'Notification/EVENT_RESOLVE', // Deprecated in favor of EVENT_USER_REWARD
    EVENT_CANCEL: 'Notification/EVENT_CANCEL', // Deprecated in favor of EVENT_USER_REWARD
    EVENT_NEW_REWARD: 'Notification/EVENT_NEW_REWARD', // Deprecated in favor of EVENT_USER_REWARD
    // User-related events
    EVENT_USER_SIGNED_IN: `Notification/EVENT_USER_SIGNED_IN`,
    EVENT_USER_SIGNED_UP: `Notification/EVENT_USER_SIGNED_UP`,
    EVENT_USER_FORGOT_PASSWORD: `Notification/EVENT_USER_FORGOT_PASSWORD`,
    EVENT_USER_UPLOADED_PICTURE: `Notification/EVENT_USER_UPLOADED_PICTURE`,
    EVENT_USER_CHANGED_USERNAME: `Notification/EVENT_USER_CHANGED_USERNAME`,
    EVENT_USER_CHANGED_NAME: `Notification/EVENT_USER_CHANGED_NAME`,
    EVENT_USER_CHANGED_PASSWORD: `Notification/EVENT_USER_CHANGED_PASSWORD`,
    EVENT_USER_UPDATED_EMAIL_PREFERENCES: `Notification/EVENT_USER_UPDATED_EMAIL_PREFERENCES`,
    EVENT_USER_SET_CURRENCY: `Notification/EVENT_USER_SET_CURRENCY`,
    EVENT_USER_REWARD: 'Notification/EVENT_USER_REWARD',
    // Event related events
    EVENT_ONLINE: 'Notification/EVENT_ONLINE',
    EVENT_OFFLINE: 'Notification/EVENT_OFFLINE',
    EVENT_NEW: 'Notification/EVENT_NEW',
    EVENT_UPDATED: 'Notification/EVENT_UPDATED',
    EVENT_NEW_BET: 'Notification/EVENT_NEW_BET',
    // Bet related events
    EVENT_BET_PLACED: 'Notification/EVENT_BET_PLACED',
    EVENT_BET_STARTED: 'Notification/EVENT_BET_STARTED',
    EVENT_BET_CASHED_OUT: 'Notification/EVENT_BET_CASHED_OUT',
    EVENT_BET_RESOLVED: 'Notification/EVENT_BET_RESOLVED',
    EVENT_BET_EVALUATED: 'Notification/EVENT_BET_EVALUATED',
    EVENT_BET_DISPUTED: 'Notification/EVENT_BET_DISPUTED',
    EVENT_BET_CANCELED: 'Notification/EVENT_BET_CANCELED',
    // ###### REWARDS BEGIN ######
    // [Reward system] General related events
    EVENT_REWARD_SIGNED_UP_WITH_INFLUENCER: 'Notification/EVENT_REWARD_SIGNED_UP_WITH_INFLUENCER',
    EVENT_REWARD_FRIEND_REFERRED: 'Notification/EVENT_REWARD_FRIEND_REFERRED',
    EVENT_REWARD_LINK_SHARED: 'Notification/EVENT_REWARD_LINK_SHARED',
    EVENT_REWARD_FEEDBACK_ANSWERED: 'Notification/EVENT_REWARD_FEEDBACK_ANSWERED',
    EVENT_REWARD_DAILY_LOGGED_IN: 'Notification/EVENT_REWARD_DAILY_LOGGED_IN',
    EVENT_REWARD_USER_CAME_BACK_AFTER_INACTIVITY: 'Notification/EVENT_REWARD_USER_CAME_BACK_AFTER_INACTIVITY',
    // [Reward system] Easter eggs related events
    EVENT_REWARD_EG_BETTED_MAX_STAKE_IN_ROW: 'Notification/EVENT_REWARD_EG_BETTED_MAX_STAKE_IN_ROW',
    EVENT_REWARD_EG_PLAYED_X_TIMES_ROSI_GAME: 'Notification/EVENT_REWARD_EG_PLAYED_X_TIMES_ROSI_GAME',
    EVENT_REWARD_EG_USER_WAS_ACTIVE_MORE_THAN_X: 'Notification/EVENT_REWARD_EG_USER_WAS_ACTIVE_MORE_THAN_X',
    EVENT_REWARD_EG_USER_PLAYED_X_DAYS_IN_ROW: 'Notification/EVENT_REWARD_EG_USER_PLAYED_X_DAYS_IN_ROW',
    EVENT_REWARD_EG_USER_PROVIDED_BIRTH_DATE: 'Notification/EVENT_REWARD_EG_USER_PROVIDED_BIRTH_DATE',
    EVENT_REWARD_EG_USER_CHECKED_IN_X_DIF_CHATS: 'Notification/EVENT_REWARD_EG_USER_CHECKED_IN_X_DIF_CHATS',
    EVENT_REWARD_EG_USER_BETTED_X_TIMES_IN_SOCIETY_CATS: 'Notification/EVENT_REWARD_EG_USER_BETTED_X_TIMES_IN_SOCIETY_CATS',
    EVENT_REWARD_EG_USER_FEEDBACK_PROVIDED: 'Notification/EVENT_REWARD_EG_USER_FEEDBACK_PROVIDED',
    // [Reward system] Weekly Leader Board related events
    EVENT_REWARD_WEEKLY_LEADERBOARD_PLACE_X_WON: 'Notification/EVENT_REWARD_WEEKLY_LEADERBOARD_PLACE_X_WON',
    // [Reward system] Monthly Leader Board related events
    EVENT_REWARD_MONTHLY_LEADERBOARD_PLACE_X_WON: 'Notification/EVENT_REWARD_MONTHLY_LEADERBOARD_PLACE_X_WON',
    // [Reward system] Milestones related events
    EVENT_REWARD_MS_BETTED_X_TIMES: 'Notification/EVENT_REWARD_MS_BETTED_X_TIMES',
    EVENT_REWARD_MS_PLAYED_X_TIMES_ROSI_GAME: 'Notification/EVENT_REWARD_MS_PLAYED_X_TIMES_ROSI_GAME',
    EVENT_REWARD_MS_REFERRED_FRIEND_X_TIMES: 'Notification/EVENT_REWARD_MS_REFERRED_FRIEND_X_TIMES',
    // [Reward system] Stages (Badges) related events
    EVENT_REWARD_BADGE_PLACED_X_BETS: 'Notification/EVENT_REWARD_BADGE_PLACED_X_BETS',
    EVENT_REWARD_BADGE_PLACED_ROSI_GAME_X_TIMES: 'Notification/EVENT_REWARD_BADGE_PLACED_ROSI_GAME_X_TIMES',
    EVENT_REWARD_BADGE_HAD_TURNOVER_X_PERCENT: 'Notification/EVENT_REWARD_BADGE_HAD_TURNOVER_X_PERCENT',
    EVENT_REWARD_BADGE_REFERRED_FRIEND_X_TIMES: 'Notification/EVENT_REWARD_BADGE_REFERRED_FRIEND_X_TIMES',
    // [Reward system] NOTIFICATIONS, general notification event for rewards
    EVENT_REWARD_NOTIFICATION_ABOUT_X: 'Notification/EVENT_REWARD_NOTIFICATION_ABOUT_X'
    // ###### REWARDS END ######
};

exports.notificationEvents = notificationEvents

const eventTypes = [...Object.values(notificationEvents)]

exports.universalEventTypes = eventTypes

